name: 'Demo push files'

on:
  push:
    paths:
      - .github/workflows/demo-push-files.yml
      - hello.txt

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: cat hello.txt
